-- DESTORY RELATIONS SCRIPT
-- FKS
ALTER TABLE plays DROP CONSTRAINT IF EXISTS fk_gid;
ALTER TABLE plays DROP CONSTRAINT IF EXISTS fk_pid;
ALTER TABLE plays DROP CONSTRAINT IF EXISTS fk_tid;
ALTER TABLE players DROP CONSTRAINT IF EXISTS fk_tid;
ALTER TABLE matchups DROP CONSTRAINT IF EXISTS fk_htid;
ALTER TABLE matchups DROP CONSTRAINT IF EXISTS fk_atid;

-- INDEXES
DROP INDEX IF EXISTS plays_pid_idx;
DROP INDEX IF EXISTS teams_tid;
DROP INDEX IF EXISTS players_pid;
DROP INDEX IF EXISTS players_tid;
DROP INDEX IF EXISTS matchups_gid;

-- PKS
ALTER TABLE plays DROP CONSTRAINT IF EXISTS pk_plays;
ALTER TABLE matchups DROP CONSTRAINT IF EXISTS pk_matchups;
ALTER TABLE players DROP CONSTRAINT IF EXISTS pk_players;
ALTER TABLE teams DROP CONSTRAINT IF EXISTS pk_teams;

