export const teams = [
  {
    id: 1610612737,
    full_name: "Atlanta Hawks",
    abbreviation: "ATL",
    nickname: "Hawks",
    city: "Atlanta",
    state: "Atlanta",
    year_founded: 1949,
    conf: "East",
  },
  {
    id: 1610612738,
    full_name: "Boston Celtics",
    abbreviation: "BOS",
    nickname: "Celtics",
    city: "Boston",
    state: "Massachusetts",
    year_founded: 1946,
    conf: "East",
  },
  {
    id: 1610612751,
    full_name: "Brooklyn Nets",
    abbreviation: "BKN",
    nickname: "Nets",
    city: "Brooklyn",
    state: "New York",
    year_founded: 1976,
    conf: "East",
  },
  {
    id: 1610612766,
    full_name: "Charlotte Hornets",
    abbreviation: "CHA",
    nickname: "Hornets",
    city: "Charlotte",
    state: "North Carolina",
    year_founded: 1988,
    conf: "East",
  },
  {
    id: 1610612741,
    full_name: "Chicago Bulls",
    abbreviation: "CHI",
    nickname: "Bulls",
    city: "Chicago",
    state: "Illinois",
    year_founded: 1966,
    conf: "East",
  },
  {
    id: 1610612739,
    full_name: "Cleveland Cavaliers",
    abbreviation: "CLE",
    nickname: "Cavaliers",
    city: "Cleveland",
    state: "Ohio",
    year_founded: 1970,
    conf: "East",
  },
  {
    id: 1610612765,
    full_name: "Detroit Pistons",
    abbreviation: "DET",
    nickname: "Pistons",
    city: "Detroit",
    state: "Michigan",
    year_founded: 1948,
    conf: "East",
  },
  {
    id: 1610612754,
    full_name: "Indiana Pacers",
    abbreviation: "IND",
    nickname: "Pacers",
    city: "Indiana",
    state: "Indiana",
    year_founded: 1976,
    conf: "East",
  },
  {
    id: 1610612748,
    full_name: "Miami Heat",
    abbreviation: "MIA",
    nickname: "Heat",
    city: "Miami",
    state: "Florida",
    year_founded: 1988,
    conf: "East",
  },
  {
    id: 1610612749,
    full_name: "Milwaukee Bucks",
    abbreviation: "MIL",
    nickname: "Bucks",
    city: "Milwaukee",
    state: "Wisconsin",
    year_founded: 1968,
    conf: "East",
  },
  {
    id: 1610612752,
    full_name: "New York Knicks",
    abbreviation: "NYK",
    nickname: "Knicks",
    city: "New York",
    state: "New York",
    year_founded: 1946,
    conf: "East",
  },
  {
    id: 1610612753,
    full_name: "Orlando Magic",
    abbreviation: "ORL",
    nickname: "Magic",
    city: "Orlando",
    state: "Florida",
    year_founded: 1989,
    conf: "East",
  },
  {
    id: 1610612755,
    full_name: "Philadelphia 76ers",
    abbreviation: "PHI",
    nickname: "76ers",
    city: "Philadelphia",
    state: "Pennsylvania",
    year_founded: 1949,
    conf: "East",
  },
  {
    id: 1610612761,
    full_name: "Toronto Raptors",
    abbreviation: "TOR",
    nickname: "Raptors",
    city: "Toronto",
    state: "Ontario",
    year_founded: 1995,
    conf: "East",
  },
  {
    id: 1610612764,
    full_name: "Washington Wizards",
    abbreviation: "WAS",
    nickname: "Wizards",
    city: "Washington",
    state: "District of Columbia",
    year_founded: 1961,
    conf: "East",
  },
  {
    id: 1610612742,
    full_name: "Dallas Mavericks",
    abbreviation: "DAL",
    nickname: "Mavericks",
    city: "Dallas",
    state: "Texas",
    year_founded: 1980,
    conf: "West",
  },
  {
    id: 1610612743,
    full_name: "Denver Nuggets",
    abbreviation: "DEN",
    nickname: "Nuggets",
    city: "Denver",
    state: "Colorado",
    year_founded: 1976,
    conf: "West",
  },
  {
    id: 1610612744,
    full_name: "Golden State Warriors",
    abbreviation: "GSW",
    nickname: "Warriors",
    city: "Golden State",
    state: "California",
    year_founded: 1946,
    conf: "West",
  },
  {
    id: 1610612745,
    full_name: "Houston Rockets",
    abbreviation: "HOU",
    nickname: "Rockets",
    city: "Houston",
    state: "Texas",
    year_founded: 1967,
    conf: "West",
  },
  {
    id: 1610612746,
    full_name: "Los Angeles Clippers",
    abbreviation: "LAC",
    nickname: "Clippers",
    city: "Los Angeles",
    state: "California",
    year_founded: 1970,
    conf: "West",
  },
  {
    id: 1610612747,
    full_name: "Los Angeles Lakers",
    abbreviation: "LAL",
    nickname: "Lakers",
    city: "Los Angeles",
    state: "California",
    year_founded: 1948,
    conf: "West",
  },
  {
    id: 1610612763,
    full_name: "Memphis Grizzlies",
    abbreviation: "MEM",
    nickname: "Grizzlies",
    city: "Memphis",
    state: "Tennessee",
    year_founded: 1995,
    conf: "West",
  },
  {
    id: 1610612750,
    full_name: "Minnesota Timberwolves",
    abbreviation: "MIN",
    nickname: "Timberwolves",
    city: "Minnesota",
    state: "Minnesota",
    year_founded: 1989,
    conf: "West",
  },
  {
    id: 1610612740,
    full_name: "New Orleans Pelicans",
    abbreviation: "NOP",
    nickname: "Pelicans",
    city: "New Orleans",
    state: "Louisiana",
    year_founded: 2002,
    conf: "West",
  },
  {
    id: 1610612760,
    full_name: "Oklahoma City Thunder",
    abbreviation: "OKC",
    nickname: "Thunder",
    city: "Oklahoma City",
    state: "Oklahoma",
    year_founded: 1967,
    conf: "West",
  },
  {
    id: 1610612756,
    full_name: "Phoenix Suns",
    abbreviation: "PHX",
    nickname: "Suns",
    city: "Phoenix",
    state: "Arizona",
    year_founded: 1968,
    conf: "West",
  },
  {
    id: 1610612757,
    full_name: "Portland Trail Blazers",
    abbreviation: "POR",
    nickname: "Trail Blazers",
    city: "Portland",
    state: "Oregon",
    year_founded: 1970,
    conf: "West",
  },
  {
    id: 1610612758,
    full_name: "Sacramento Kings",
    abbreviation: "SAC",
    nickname: "Kings",
    city: "Sacramento",
    state: "California",
    year_founded: 1948,
    conf: "West",
  },
  {
    id: 1610612759,
    full_name: "San Antonio Spurs",
    abbreviation: "SAS",
    nickname: "Spurs",
    city: "San Antonio",
    state: "Texas",
    year_founded: 1976,
    conf: "West",
  },
  {
    id: 1610612762,
    full_name: "Utah Jazz",
    abbreviation: "UTA",
    nickname: "Jazz",
    city: "Utah",
    state: "Utah",
    year_founded: 1974,
    conf: "West",
  },
];
